const Data = [
  { id: 1, src: "table1.png", alt: "Table 1", category: "Dining" },
  { id: 2, src: "table2.png", alt: "Table 2", category: "Dining" },
  { id: 3, src: "table3.png", alt: "Table 3", category: "Dining" },
  { id: 4, src: "table4.png", alt: "Table 4", category: "Dining" },
  { id: 5, src: "table6.png", alt: "Table 6", category: "Dining" },
  { id: 6, src: "table7.png", alt: "Table 7", category: "Dining" },
  { id: 7, src: "table8.png", alt: "Table 8", category: "Dining" },
  { id: 8, src: "table9.png", alt: "Table 9", category: "Dining" },
  { id: 9, src: "table10.png", alt: "Table 10", category: "Dining" },
  { id: 10, src: "table11.png", alt: "Table 11", category: "Dining" },
  { id: 11, src: "table12.png", alt: "Table 12", category: "Dining" },
  { id: 12, src: "table13.png", alt: "Table 13", category: "Dining" },
  { id: 13, src: "table14.png", alt: "Table 14", category: "Dining" },
  { id: 14, src: "table16.png", alt: "Table 16", category: "Dining" },
  { id: 15, src: "table17.png", alt: "Table 17", category: "Dining" },
  { id: 16, src: "table18.png", alt: "Table 18", category: "Dining" },
  { id: 17, src: "table20.png", alt: "Table 20", category: "Dining" },
  { id: 18, src: "table21.png", alt: "Table 21", category: "Dining" },
  { id: 19, src: "table22.png", alt: "Table 22", category: "Dining" },
  { id: 20, src: "table23.png", alt: "Table 23", category: "Dining" },
  { id: 21, src: "table25.png", alt: "Table 25", category: "Dining" },
  { id: 22, src: "table26.png", alt: "Table 26", category: "Dining" },
  { id: 23, src: "table27.png", alt: "Table 27", category: "Dining" },
  { id: 24, src: "table28.png", alt: "Table 28", category: "Dining" },
  { id: 25, src: "table29.png", alt: "Table 29", category: "Dining" },
  { id: 26, src: "table31.png", alt: "Table 31", category: "Dining" },
  { id: 27, src: "table32.png", alt: "Table 32", category: "Dining" },
  { id: 28, src: "table34.png", alt: "Table 34", category: "Dining" },
  { id: 29, src: "table35.png", alt: "Table 35", category: "Dining" },
  { id: 30, src: "table36.png", alt: "Table 36", category: "Dining" },
  { id: 31, src: "table37.png", alt: "Table 37", category: "Dining" },
  { id: 32, src: "table38.png", alt: "Table 38", category: "Dining" },
  { id: 33, src: "table40.png", alt: "Table 40", category: "Dining" },
  { id: 34, src: "table41.png", alt: "Table 41", category: "Dining" },
  { id: 35, src: "table42.png", alt: "Table 42", category: "Dining" },
  { id: 36, src: "table43.png", alt: "Table 43", category: "Dining" },
  { id: 37, src: "table44.png", alt: "Table 44", category: "Dining" },
  { id: 38, src: "table45.png", alt: "Table 45", category: "Dining" },
  { id: 39, src: "table48.png", alt: "Table 48", category: "Dining" },
  { id: 40, src: "table49.png", alt: "Table 49", category: "Dining" },
  { id: 41, src: "table53.png", alt: "Table 53", category: "Dining" },
  { id: 42, src: "table54.png", alt: "Table 54", category: "Dining" },
  { id: 43, src: "table55.png", alt: "Table 55", category: "Dining" },
  { id: 44, src: "table56.png", alt: "Table 56", category: "Dining" },
  { id: 45, src: "table57.png", alt: "Table 57", category: "Dining" },
  { id: 46, src: "table58.png", alt: "Table 58", category: "Dining" },
  { id: 47, src: "table60.png", alt: "Table 60", category: "Dining" },
  { id: 48, src: "office1.png", alt: "Desk 1", category: "Office" },
  { id: 49, src: "office2.png", alt: "Desk 1", category: "Office" },
  { id: 50, src: "office3.png", alt: "Desk 2", category: "Office" },
  { id: 51, src: "kitchen1.png", alt: "Kitchen 1", category: "Kitchen" },
  { id: 52, src: "kitchen2.png", alt: "Kitchen 2", category: "Kitchen" },
  { id: 53, src: "living10.png", alt: "Living Room 10", category: "Living Room" },
  { id: 54, src: "living11.png", alt: "Living Room 11", category: "Living Room" },
  { id: 55, src: "living12.png", alt: "Living Room 12", category: "Living Room" },
  { id: 56, src: "living6.png", alt: "Living Room 6", category: "Living Room" },
  { id: 57, src: "living7.png", alt: "Living Room 7", category: "Living Room" },
  { id: 58, src: "living8.png", alt: "Living Room 8", category: "Living Room" },
  { id: 59, src: "living2.png", alt: "Living Room 2", category: "Living Room" },
  { id: 60, src: "living3.png", alt: "Living Room 3", category: "Living Room" },
  { id: 61, src: "living4.png", alt: "Living Room 4", category: "Living Room" },
  { id: 62, src: "living5.png", alt: "Living Room 5", category: "Living Room" },
  { id: 63, src: "living1.png", alt: "Living Room 1", category: "Living Room" },
  { id: 64, src: "living13.png", alt: "Living Room 1", category: "Living Room" },
  { id: 65, src: "bedroom1.png", alt: "Bedroom 1", category: "Bedroom" },  
  { id: 66, src: "commercial3.png", alt: "Commercial 3", category: "Commercial" },
  { id: 67, src: "commercial6.png", alt: "Commercial 6", category: "Commercial" },
  { id: 68, src: "commercial5.png", alt: "Commercial 5", category: "Commercial" },
  { id: 69, src: "commercial4.png", alt: "Commercial 4", category: "Commercial" },
  { id: 70, src: "commercial1.png", alt: "Commercial 1", category: "Commercial" },
  { id: 71, src: "commercial2.png", alt: "Commercial 2", category: "Commercial" },
];

export default Data;
